FROM node:16-slim

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Install node dependencies
RUN yarn install --frozen-lockfile --network-timeout 100000

# Copy the rest of the application
COPY . .

# Expose port
EXPOSE 8080

# Start the service
CMD ["yarn", "auth"]